### ISSUE TITLE
Publication was not found error.

### ISSUE THREAD

**Issue by dagdelenmustafa** [dexplo/jupyter_to_medium#1]
Hi,

Thanks for your effort to create this amazing package. But as you can see, I got an error when I tried to publish my notebook. I tried to publish on browser. 

Failed to post to Medium
Returned error message below

"ValueError('Publication Detectron2 Training on Custom COCO Dataset was not found.\\nHere is the publication data returned from Medium\\n\\n[{\\'id\\': \\'2615bd06b42e\\', \\'name\\': \\'Netflix TechBlog\\', \\'description\\': \\'Learn about Netflix\u2019s world class engineering efforts, company culture, product developments and more.\\', \\'url\\': \\'https://medium.com/netflix-techblog\\', \\'imageUrl\\': \\'https://cdn-images-1.medium.com/fit/c/400/400/1*ty4NvNrGg4ReETxqU2N3Og.png\\'}, {\\'id\\': \\'30b48a5bd390\\', \\'name\\': \\'Commencis\\', \\'description\\': \\'We help leading brands to grow and scale in digital, powered by our big data, analytics and cloud products.\\', \\'url\\': \\'https://medium.com/commencis\\', \\'imageUrl\\': \\'https://cdn-images-1.medium.com/fit/c/400/400/1*YloZr9rTylyeM5jMvNuHSQ.jpeg\\'}, {\\'id\\': \\'32881626c9c9\\', \\'name\\': \\'Data Driven Investor\\', \\'description\\': \\'from confusion to clarity not insanity\\', \\'url\\': \\'https://medium.com/datadriveninvestor\\', \\'imageUrl\\': \\'https://cdn-images-1.medium.com/fit/c/400/400/1*2mBCfRUpdSYRuf9EKnhTDQ.png\\'}, {\\'id\\': \\'7f60cf5620c9\\', \\'name\\': \\'Towards Data Science\\', \\'description\\': \\'A Medium publication sharing concepts, ideas, and codes.\\', \\'url\\': \\'https://medium.com/towards-data-science\\', \\'imageUrl\\': \\'https://cdn-images-1.medium.com/fit/c/400/400/1*hVxgUA6kP-PgL5TJjuyePg.png\\'}, {\\'id\\': \\'b230ea2a6eb8\\', \\'name\\': \\'Mission.org\\', \\'description\\': \\'A network of business & tech podcasts designed to accelerate learning. Selected as \u201cBest of 2018\u201d by Apple. Mission.org\\', \\'url\\': \\'https://medium.com/the-mission\\', \\'imageUrl\\': \\'https://cdn-images-1.medium.com/fit/c/400/400/1*kFWwYehzjJIhgw8hTygfHw.png\\'}, {\\'id\\': \\'bfe0867c7b05\\', \\'name\\': \\'Medium T\u00fcrk\u00e7e\\', \\'description\\': \\'Resmi T\u00fcrk\u00e7e Yay\u0131n\\', \\'url\\': \\'https://medium.com/turkce\\', \\'imageUrl\\': \\'https://cdn-images-1.medium.com/fit/c/400/400/1*6_fgYnisCa9V21mymySIvA.png\\'}, {\\'id\\': \\'c659d22bee68\\', \\'name\\': \\'trendyol tech\\', \\'description\\': \\'Trendyol Tech Team\\', \\'url\\': \\'https://medium.com/trendyol-tech\\', \\'imageUrl\\': \\'https://cdn-images-1.medium.com/fit/c/400/400/1*posh7DaGCQA8Ku-qkxrdyQ.jpeg\\'}, {\\'id\\': \\'e41678be55e9\\', \\'name\\': \\'X, the moonshot factory\\', \\'description\\': \\'News and insights from the team at X. For more info visit us at http://www.x.company/\\', \\'url\\': \\'https://medium.com/thexblog\\', \\'imageUrl\\': \\'https://cdn-images-1.medium.com/fit/c/400/400/1*RUmNT7_BGs42cw0HxhMtMg.jpeg\\'}, {\\'id\\': \\'fd4c083fbb93\\', \\'name\\': \"Sicara\\'s blog\", \\'description\\': \\'We build tailor-made AI and Big Data solutions for amazing clients\\', \\'url\\': \\'https://medium.com/sicara\\', \\'imageUrl\\': \\'https://cdn-images-1.medium.com/fit/c/400/400/1*8Fza8Hkhvp9nAW7HOnsQbA.png\\'}]')"

**Comment by tdpetrou** [comment]
Hi there,

You need to provide the Medium publication name in the publication name text box. 

Leave this field blank if you want to post it under your name without being attached to a publication.

As you can see in the returned error data, you've published on multiple publications

* Netflix TechBlog
* Data Driven Investor
* Towards Data Science
* Mission.org
etc...

Those are the publication names. 

The publication name is NOT the title of the post.

Can you try again and either leave the publication name blank or use one of the actual publications that you've contributed to.

**Comment by dagdelenmustafa** [comment]
Yes I didn't watch out this remark. I tried again and it was successfully published :) Thanks.

**Comment by tdpetrou** [comment]
@dagdelenmustafa Great! Do you have a link to your post?

Also, if you could help spread the word about how this was done (perhaps with a link at the bottom of your post), that would be nice. Thanks for testing it out!

**Comment by dagdelenmustafa** [comment]
Hi @tdpetrou ,

I saw your advice so late but i promise I will share your package's link in my next post :)
Here is my last published post, hope you like it. https://medium.com/@mdagdelen/detectron2-training-on-custom-coco-dataset-b0e8d4b6b3b

**Comment by tdpetrou** [comment]
Thanks for sharing. Please think about editing your post on Medium to cite this tool which will allow others to help find it.
