### ISSUE TITLE
Various cosmetic bugs using a full Data Science notebook

### ISSUE THREAD

**Issue by etzimopoulos** [dexplo/jupyter_to_medium#10]
Hi Ted,

This is looking great so far. I've run a full data science notebook from a project I did back in Feb and here are some issues I've noticed:

1. URL links in the markdown are not translated as Links. i.e. I had a contents page with navigation links
2.  Tables in Markdown are not translated as Images e.g. Look at "Key Attributes Information" or "Project Planning & Key Milestones" sections
3. Summary of Initial Data Review Section - Some of the Numbering is lost and all sections appear as 1. (instead of 1.  2. 3. 4. etc...). Some sections were ok and some not, so not sure why this happens.4. 

Feel free to run it yourself and compare the output in Medium with the notebook to see what needs fixing or if you can spot something else yourself.

Attached files here.
[GA-Capstone-Project-Customer-Segmentation-Using- RFM-Clustering.zip](https://github.com/dexplo/jupyter_to_medium/files/4840036/GA-Capstone-Project-Customer-Segmentation-Using-.RFM-Clustering.zip)

Thanks
Angelo

**Comment by tdpetrou** [comment]
Thanks for sending this test notebook. 

1. Within-page navigation links, called "anchor links" are not supported by Medium. If you do an online search for "medium anchor links", you'll see various hacks to get this to work. Regular links (http) will work
2. Markdown tables are next on my list of things to do. I'll have to write a regex to find them, or convert it to html first.
3. Nested lists aren't supported by Medium, so anytime you have one, the list won't work properly.

**Comment by etzimopoulos** [comment]
Great thank you for pointing 1 and 3 out, I'll keep that in mind so I can publish seamlessly to Medium. 

Markdown tables I haven't used much, but would be great feature to add at some point.

**Comment by tdpetrou** [comment]
Just released version 0.2 with support for markdown tables. If you can test it out and let me know what you think, that'd be great.
