### ISSUE TITLE
Problem with latex

### ISSUE THREAD

**Issue by greatsharma** [dexplo/jupyter_to_medium#11]
First off thank you for such an API. Using this I just published my very first medium story. While publishing my 2nd story which contains lots of latex code, this API is unable to parse it. I tried [this](https://www.kaggle.com/gauravsharma99/statistical-analysis-on-mpg-data) notebook.

**Comment by tdpetrou** [comment]
Thanks!

I didn't think about parsing LaTex, so this is something to consider for the future. Medium doesn't handle LaTeX so I'm guessing, an image will need to be created for it.

**Comment by greatsharma** [comment]
okay, thank-you
