### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ronakkjain** [dexplo/jupyter_to_medium#12]
I already have the file at location but after clicking on publish it says Failed to post to Medium
Returned error message below
"[Errno 2] No such file or directory:

**Comment by tdpetrou** [comment]
Can you give more specifics on this? 



Operating system? 
jupyter_to_medium version?


Make sure you've upgraded to version 0.1.1

**Comment by ronakkjain** [comment]
All latest version till date.

**Comment by tdpetrou** [comment]
You might be getting the error because of an image file that in the markdown that does not exist. Upgrade to 0.2.2 and you'll get the entire message. This is what caused an error in issue #13.
