### ISSUE TITLE
Pandas tables don't  appear in the published 

### ISSUE THREAD

**Issue by KVSSetty** [dexplo/jupyter_to_medium#13]
Trying this little cutey package and published a article in medium and linked here and liked the package very much, but one sad thing is I don't see the pandas tables ? why? 
the link to the article is here:
[here](https://medium.com/@kvssetty/how-to-handel-missing-data-71a3eb89ef91)

**Comment by tdpetrou** [comment]
Can you zip your notebook and attach it here in another comment?

**Comment by KVSSetty** [comment]
Hello,
Here is the compressed zip of the note book
Thanks and Regards
KVS Setty

**Comment by KVSSetty** [comment]
Sorry I did not attach  zip file in the previous post ,please find it here.
[How to Handle Missing Data with Python.zip](https://github.com/dexplo/jupyter_to_medium/files/4874554/How.to.Handle.Missing.Data.with.Python.zip)

**Comment by tdpetrou** [comment]
Just looked at your notebook. You are referencing the image How-to-Handle-Missing-Values-with-Python.jpg, but it doesn't exist. This isn't an issue with jupyter to medium. You need to find that image and place it in that directory with the notebook.
