### ISSUE TITLE
Add changelog/releases to GitHub

### ISSUE THREAD

**Issue by discdiver** [dexplo/jupyter_to_medium#14]
I updated to the latest version. Works great! I like to know what the changes between versions are before upgrading and look first in the releases section on GitHub. I'm guessing other folks do too. Thanks again for the package!

**Comment by tdpetrou** [comment]
Thanks for commenting on this. I was unaware of github releases, but will start making them. Here is my first attempt - https://github.com/dexplo/jupyter_to_medium/releases/tag/0.2.3
