### ISSUE TITLE
plots and animations not rendering 

### ISSUE THREAD

**Issue by kurtispykes** [dexplo/jupyter_to_medium#15]
I've written a post and published it as a draft on Medium, but when I go onto Medium my plots do not render as images. Instead I get the result of the image below.

Additionally, I used matplotlib animation and used Ipython.display.HTML to display the animation. The result I get says "Your browser does not support the video tag." however I am using the suggested browser which is chrome. 
<img width="584" alt="plot" src="https://user-images.githubusercontent.com/43003716/88078202-165c1600-cb74-11ea-8b21-10c0cfff1038.png">

**Comment by tdpetrou** [comment]
Can you attach your entire notebook file here?

Regarding videos - Medium does not allow them.

**Comment by kurtispykes** [comment]
https://github.com/kurtispykes/demo/blob/master/notebook/kpy_jupyter_to_medium_test.ipynb

**Comment by tdpetrou** [comment]
Thanks, I just tested it on my end and it is working as expected.

Can you verify what version of jupyter to medium you have?

```
import jupyter_to_medium
jupyter_to_medium.__version__
```

The latest version is 0.2.2

Also, what OS are you running?


<img width="776" alt="Screen Shot 2020-07-22 at 9 51 37 AM" src="https://user-images.githubusercontent.com/7226751/88184687-06d6de80-cc01-11ea-950a-14182d30d13e.png">

**Comment by kurtispykes** [comment]
I have jupyter_to_medium 0.2.2 installed also 

system type: 64-bit operating system, x64-based processor 
edition: Windows 10 Enterprise
version: 1809

**Comment by kurtispykes** [comment]
What version of Python are you using please? If it is different to the one I am using  (Python 3.8.3) I will the same one as you to see if maybe that could be the problem.

**Comment by tdpetrou** [comment]
I just fixed this. There was a bug on windows systems. I just tested your notebook on a windows installation and verified that it worked.

Can you upgrade to version 0.2.3 and try again? If it works, please close this issue. Thanks very much for reporting this!
