### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1501: character maps to <undefined>

### ISSUE THREAD

**Issue by KVSSetty** [dexplo/jupyter_to_medium#17]
I  am on windows,
when i convert , I get the above error
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1501: character maps to <undefined>
what could be the problem. any suggestions
Thanks and regards
KVS Setty

**Comment by kurtispykes** [comment]
@KVSSetty Did you manage to find a solution as I am currently getting the same error? I am also using windows so I am assuming it's may be something to do with that. 

I tried rolling back to the last version of jupyter_to_medium that I used successfully (0.2.0) and it was still occuring which seem a tad odd.

**Comment by tdpetrou** [comment]
Hey @KVSSetty and @kurtispykes, can you attach your notebooks here. I'll take a look on a windows machine

**Comment by kurtispykes** [comment]
@tdpetrou https://github.com/kurtispykes/recommender_system/blob/master/notebooks/01_kpy_explorations.ipynb

**Comment by tdpetrou** [comment]
Thanks. I see the error.

Change the `get_notebook` method to this

```
def get_notebook(self):
        return nbformat.read(self.filename, as_version=4)
```

**Comment by tdpetrou** [comment]
This is now fixed in master. Thanks for reporting this  @KVSSetty and @kurtispykes!

**Comment by tdpetrou** [comment]
Hey @kurtispykes, I just bumped the version up to 0.2.4 to fix this bug. Can you upgrade and check that it works for you?

**Comment by kurtispykes** [comment]
Hey @tdpetrou, 

Thanks for the update. I tried it and got the following error:

**Comment by tdpetrou** [comment]
Yea, you'll need to [install lxml](https://pypi.org/project/lxml/) to have BeautifulSoup work. But don't use the matplotlib version. It's just a backup for those that don't have chrome installed.
