### ISSUE TITLE
Possibility to center the dataframe on the image.

### ISSUE THREAD

**Issue by paduel** [dexplo/jupyter_to_medium#2]
Fantastic job, @tdpetrou .

I'm using Jupyter to Medium and it works like a charm.

In some cases the dataframes are not very wide, would it be possible to have the table centered in the image as an option?

Thank you.

**Comment by paduel** [comment]
Graphically.

Now:![left_align](https://user-images.githubusercontent.com/5903320/83967022-426e5100-a8be-11ea-91db-79386bfe84c3.png)

To be able to select an output like this.
![center_align](https://user-images.githubusercontent.com/5903320/83967021-3aaeac80-a8be-11ea-9765-fba74731565f.png)

**Comment by tdpetrou** [comment]
Thanks for submitting this. I think centering should be the default and probably only option here. It was left-aligned because that's how it appears in the notebook, but for Medium, it should be centered. I'll add this soon.

**Comment by paduel** [comment]
A pleasure to be able to collaborate minimally.

I close this issue.

**Comment by tdpetrou** [comment]
Thanks @paduel very much for this. I've added it to the master branch and will have it in the next update.
