### ISSUE TITLE
Today suddenly not generating the medium blog.

### ISSUE THREAD

**Issue by rohan-paul** [dexplo/jupyter_to_medium#24]
After I did deploy to medium getting the below error. 

Google Chrome and Ubuntu 20.04 machine.

`FileNotFoundError` error that I am getting for an image URL, that's a valid URL and it indeed has the image.

```
Failed to post to Medium
Returned error message below

"FileNotFoundError: [Errno 2] No such file or directory: '![img](https:/i.imgur.com/z4BauDL.png'

Traceback (most recent call last):
File \"/home/paul/anaconda3/lib/python3.7/site-packages/jupyter_to_medium/_bundler.py\", line 37, in upload
data = publish(**kwargs)
File \"/home/paul/anaconda3/lib/python3.7/site-packages/jupyter_to_medium/_publish_to_medium.py\", line 300, in publish
p.main()
File \"/home/paul/anaconda3/lib/python3.7/site-packages/jupyter_to_medium/_publish_to_medium.py\", line 218, in main
self.md, self.image_data_dict = self.create_markdown()
File \"/home/paul/anaconda3/lib/python3.7/site-packages/jupyter_to_medium/_publish_to_medium.py\", line 118, in create_markdown
mp.preprocess(self.nb, self.resources)
File \"/home/paul/anaconda3/lib/python3.7/site-packages/nbconvert/preprocessors/base.py\", line 69, in preprocess
nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
File \"/home/paul/anaconda3/lib/python3.7/site-packages/jupyter_to_medium/_preprocesors.py\", line 88, in preprocess_cell
image_data = open(nb_home / image_file, 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: '![img](https:/i.imgur.com/z4BauDL.png'
```

**Comment by mjam03** [comment]
Hello again,

I've had a quick look at this and although the url is valid the package doesn't currently support converting embedded images that are not stored locally. In the `MarkdownPreprocessor` class that extends the default `Preprocessor` class from `nbconvert`, the code picks up these files as images and searches for their local location.

I've added a fix for this that:
 - checks if the file name includes "https" (secure only)
 - if so uses requests to get the image data over https
 - uses this as the image data in `image_data_dict` which is then uploaded to medium and embedded in the article
 - added a test notebook for image creation that tests images from multiple different sources (local storage, 'img' tags, urls)

Will merge the change in now. Let me know if you still see problems for this!
