### ISSUE TITLE
Error discovered and fix here

### ISSUE THREAD

**Issue by mistercakes** [dexplo/jupyter_to_medium#25]
failed 'PosixPath' object has no attribute 'read'

this can be fixed by updating to nbformat==5.1.2

**Comment by mjam03** [comment]
Can you provide some more information please on when this error occurs so I can replicate and try to fix?

Not keen to fix dependencies unless necessary, especially given that nbformat is not a direct dependency but likely a dependency of nbconvert.

**Comment by mjam03** [comment]
I've re-packaged everything now to use poetry - this makes use of the poetry.lock function to ensure that all dependencies are pinned and so this issue will disappear. I've also set up Github Actions tests to run that test the package on:
 - ubuntu / mac / windows
 - python 3.7/8/9

and currently everything passes.

This will be released on PyPI in the next few days so am going to close the issue. Feel free to let me know if you still see the issue after that and I'll happily reopen.
