### ISSUE TITLE
BUG: jtm script with publish_stats='draft' leads to automatic submission to publication and publishing when 'pub_name' is included

### ISSUE THREAD

**Issue by discdiver** [dexplo/jupyter_to_medium#27]
jtm script with publish_stats='draft' leads to automatic submission to publication and publishing when 'pub_name' is included. 

I've seen this happen a few times. I would assume the `publish_status="draft"` would stop the article from being published, but it does not appear to.

```
pub_name="Towards Data Science",
title=None,
publish_status="draft",
```

**Comment by mjam03** [comment]
Hi,

I appreciate I'm responding to this months after it was raised but I'm cleaning up all old issues and wanted to look into it. I've had a look at what the behaviour of the Medium API is and I can't see how this would be happening. This is from the Medium API docs [here](https://github.com/Medium/medium-api-docs#33-posts):

![image](https://user-images.githubusercontent.com/32222534/143432314-76fbaba7-6912-4f4d-a708-75acd952ef84.png)

So the only way it's possible is if you are an Editor for TDS. And then even if this is so, `publish_status='draft'` is set here:

![image](https://user-images.githubusercontent.com/32222534/143432503-f8861e1b-9144-4c11-b7a9-94e192b50569.png)

in the package code so you would need to explicitly set `publish_status='public'`.

All that said if this is still posing a problem then pls let me know and I will re-open the issue and investigate.
