### ISSUE TITLE
Feature Proposal (PR Ready!): Option to 'Gistify' code snippets

### ISSUE THREAD

**Issue by mjam03** [dexplo/jupyter_to_medium#28]
I'm a big fan of the work already done here - thanks so much! The final hurdle for me is handling un-linted python code that sits in the article - large chunks of grey code can look uninviting and ruin the flow of the article. __I've whipped up a PR this morning to strip code out of the .md and insert a freshly created embedded gist link.__

## Feature Proposal

Add an option to on-the-fly create gists for your code blocks (over a certain threshold number of lines)

## Example

The following code that would sit in a medium post as this:

```
# output cause of death data
df_cod.to_csv('../data/df_cod.csv', index=False)

# output weekly death data
df_ed.to_csv('../data/df_ed.csv', index=False)

# output dhsc data
df_dhsc.to_csv('../data/df_dhsc.csv', index=False)
```
 would instead become an embedded link like this (already tested and in the medium editor this already shows as an embedded link):

https://gist.github.com/mjam03/a1011b3d063261a77739f2a1bfe39049

## Solution

In Publish class (post .ipynb conversion to .md by self.create_markdown) run a method to:
 - Parse the .md and strip out codeblocks
 -  For code blocks > threshold size, utilise the gist github api to on-the-fly create new gists
 -  Embed these gists into the new .md pre publish to medium

**Comment by tdpetrou** [comment]
Hey @mjam03, do you want to help maintain this project? Thanks for the pull request!

**Comment by mjam03** [comment]
Yeah I'd love to - let me know what you'd like me to look at and I can have a look!

**Comment by tdpetrou** [comment]
> Yeah I'd love to - let me know what you'd like me to look at and I can have a look!

Great. I don't really have time to do anything at the moment. So, that means help with

* Taking a look at all issues and merging pull requests
* Better documentation within the code

Let me know if you want me to add you as a maintaner.

**Comment by mjam03** [comment]
Yeah sounds good to me - I’ll start having a look at the PRs this weekend/early next week

**Comment by tdpetrou** [comment]
Ok. I think I invited you as a collaborator. After you get through the pull requests, we can release a new version. We probably need to update the tests, which if i recall correctly, are a pain to setup through github actions, but is something that needs to be done.

**Comment by mjam03** [comment]
Great, I should have some time tomorrow to start having a look

Thanks for letting me help!
Mark

**Comment by mjam03** [comment]
Hey,

Sorry completely dropped the ball no this. I’ve started going through issue tickets today and had a bit more of a look at the overall package structure.

Obviously it’s up to you, but a few things I thought would be worth doing that I’ll knock out in the following few days hopefully:
 
Add support for latex that is not embedded in the code

I thought even something basic like:
 - for all cells which are marked as markdown
 - check if they start with $$ and end with $$
 - if so strip the code and run it through a function I have that converts it to an image
 - the standard markdown cell preprocessor will then stick these images in the image_data_dict
 
Go through the setup.py and migrate this

I obviously don’t want to do anything you’re not keen on but I think using poetry might be quite useful here when there are a few dependencies that are a bit tricky (jupyter_contrib_nbextensions, nbformat etc). To dev on this locally I’m building a condo environment but I need to do that by creating an environment.yml manually from the setup.py dependencies. Using poetry with a pyproject.toml would then make it very easy to make sure the environment is consistent both for dev-ing and ensure that when the package is installed errors around nbformat versioning etc disappear.

Again, don’t want to do anything you’re not keen on but let me know if you’ve got any objections. Obviously with the second one I’ll make sure the documentation shows exactly as per it is now and make sure the mkdocs gen’ed documentation stays as it is.

Thanks again for building this package!

Mark

**Comment by mjam03** [comment]
I have finally merged this change in - closing issue
