### ISSUE TITLE
Can not see the "Deploy as" under File Menu

### ISSUE THREAD

**Issue by rohan-paul** [dexplo/jupyter_to_medium#32]
![image](https://user-images.githubusercontent.com/12703975/124192501-03232b80-dae3-11eb-9a33-df5f511b3069.png)

The jupyter_to_medium extension is enabled as you can see from the below extension-configuration screen.
 

![image](https://user-images.githubusercontent.com/12703975/124192594-251cae00-dae3-11eb-9508-41c831e97fae.png)

Also by running `jupyter nbextension list` I can see this extension is enabled.

Using Chrome Version 91.0.4472.114 (Official Build) (64-bit)
Ubuntu 20.04

**Comment by mjam03** [comment]
Hi Rohan,

Sorry for such a delay in coming back to you. I'm struggling to replicate the issue you have. Can you confirm that you are/have done the following:
 - running using `jupyter notebook` not `jupyter lab`
 - have run `pip install jupyter_to_medium`
 - have run `jupyter bundlerextension enable --py jupyter_to_medium._bundler --sys-prefix` as per Ted's comment in the README.md

If I start a fresh environment then sometimes I also don't see the "Deploy as" section, but after running that last command with the bundler function it then shows up. If you are still having problems can you post some info (like an `environment.yml` or `requirements.txt`) and I can try to replicate again.

**Comment by mjam03** [comment]
Going to close this - can reopen if still a problem / the above doesn't fix it
