### ISSUE TITLE
Failed to post to Medium

### ISSUE THREAD

**Issue by norochalise** [dexplo/jupyter_to_medium#45]
Returned error message below

"JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
File \"C:\\Users\\mountboy\\anaconda3\\lib\\site-packages\\jupyter_to_medium\\_bundler.py\", line 37, in upload
data = publish(**kwargs)
File \"C:\\Users\\mountboy\\anaconda3\\lib\\site-packages\\jupyter_to_medium\\_publish_to_medium.py\", line 300, in publish
p.main()
File \"C:\\Users\\mountboy\\anaconda3\\lib\\site-packages\\jupyter_to_medium\\_publish_to_medium.py\", line 216, in main
self.author_id = self.get_author_id()
File \"C:\\Users\\mountboy\\anaconda3\\lib\\site-packages\\jupyter_to_medium\\_publish_to_medium.py\", line 96, in get_author_id
return r.json()['data']['id']
File \"C:\\Users\\mountboy\\anaconda3\\lib\\site-packages\\requests\\models.py\", line 900, in json
return complexjson.loads(self.text, **kwargs)
File \"C:\\Users\\mountboy\\anaconda3\\lib\\json\\__init__.py\", line 357, in loads
return _default_decoder.decode(s)
File \"C:\\Users\\mountboy\\anaconda3\\lib\\json\\decoder.py\", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File \"C:\\Users\\mountboy\\anaconda3\\lib\\json\\decoder.py\", line 355, in raw_decode
raise JSONDecodeError(\"Expecting value\", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mjam03** [comment]
Hi,

Yes I'm getting the same issue - I'm going to email Medium and see what the issue is. It seems like authentication is failing when trying to pull the author ID from the Medium API.

Will keep you updated,
Mark

**Comment by norochalise** [comment]
Hi Mark,

Yes Its looks medium issue. I try to contact medium but there is another signing issue. Hope it will solve soon.  If you get any update please share it. Thank you!

Best regards,
Noro

**Comment by mjam03** [comment]
It seems to be working now for me - how is it for you?

If working then pls close the issue otherwise I'll dig into it.

Thanks,
Mark

**Comment by norochalise** [comment]
Yes, Its working. 

best regards,
Noro

**Comment by kir0ul** [comment]
Hi there,

I get a similar error:
```
Failed to post to Medium

Returned error message below

"JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
File \"/home/apierre/Dev/tuto-frozenlake/.direnv/python-3.10.4/lib/python3.10/site-packages/requests/models.py\", line 971, in json
return complexjson.loads(self.text, **kwargs)
File \"/home/apierre/.pyenv/versions/3.10.4/lib/python3.10/json/__init__.py\", line 346, in loads
return _default_decoder.decode(s)
File \"/home/apierre/.pyenv/versions/3.10.4/lib/python3.10/json/decoder.py\", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File \"/home/apierre/.pyenv/versions/3.10.4/lib/python3.10/json/decoder.py\", line 355, in raw_decode
raise JSONDecodeError(\"Expecting value\", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File \"/home/apierre/Dev/tuto-frozenlake/.direnv/python-3.10.4/lib/python3.10/site-packages/jupyter_to_medium/_bundler.py\", line 71, in upload
data = publish(**kwargs)
File \"/home/apierre/Dev/tuto-frozenlake/.direnv/python-3.10.4/lib/python3.10/site-packages/jupyter_to_medium/_publish_to_medium.py\", line 449, in publish
p.main()
File \"/home/apierre/Dev/tuto-frozenlake/.direnv/python-3.10.4/lib/python3.10/site-packages/jupyter_to_medium/_publish_to_medium.py\", line 306, in main
self.author_id = self.get_author_id()
File \"/home/apierre/Dev/tuto-frozenlake/.direnv/python-3.10.4/lib/python3.10/site-packages/jupyter_to_medium/_publish_to_medium.py\", line 134, in get_author_id
return r.json()[\"data\"][\"id\"]
File \"/home/apierre/Dev/tuto-frozenlake/.direnv/python-3.10.4/lib/python3.10/site-packages/requests/models.py\", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"
```
Any idea what's happening?
