### ISSUE TITLE
Notebook kernel keeps dying

### ISSUE THREAD

**Issue by namiyousef** [dexplo/jupyter_to_medium#49]
Hi,

When I try to use this package, my kernel cannot connect.
<img width="150" alt="Screenshot 2022-02-01 at 21 56 14" src="https://user-images.githubusercontent.com/64047828/152058168-c5208be7-291f-4ce6-ba5e-c676efa25d1e.png">
Any help with this?

I'm running this on Python 3.7.0 on Big Sur. The only commands I've run on the virtualenv have been:
`pip install notebook`
`pip install jupyter_to_medium`

Because the 'deploy' feature wasn't showing up, I had to try the manual fix `jupyter bundlerextension enable --py jupyter_to_medium._bundler --sys-prefix`

It now does show, but I am unable to connect to the kernel.

Any help would be appreciated.

**Comment by mjam03** [comment]
Hi,

Is this still an issue? If so, can you post more detail about it? I can't replicate anything like that.

Going to close the issue for now - will reopen if you are still having problems and look into it.

Mark
