### ISSUE TITLE
Apple M1: Installing the package results in 500 internal server error. With possible fix.

### ISSUE THREAD

**Issue by simpleParadox** [dexplo/jupyter_to_medium#52]
I'm using miniconda and I already have jupyter notebook installed using `pip install notebook`. Then when I install jupyter_to_medium using conda, I encounter a 500 internal server error while opening up the notebook. Even after that, I couldn't even load up jupyter.

After a lot of googling I found something that works: 
First uninstall jupyter notebook.

Then install the package using `conda install -c conda-forge jupyter_to_medium`
Then install jupyter notebook using `pip install notebook`.
Upgrade nbconvert using `pip install nbconvert --upgrade`

Hopefully this is somehow integrated in an update.

Thanks again for the wonderful package :)

**Comment by mjam03** [comment]
Hi there,

Apologies for not getting back to you at the time when you raised this issue.

I've just bumped the package dependencies so we're using more recent versions - especially of nbconvert from `5.6.1` to `7.2.10`

Do let me know if this is still an issue.

Thanks,
Mark

**Comment by mjam03** [comment]
I _think_ this should have been solved by the package updates i made a few days ago - I'm going to close for now but if this persists pls do let me know and i'll just reopen and fix.

Mark
