### ISSUE TITLE
Error while Posting

### ISSUE THREAD

**Issue by pavankalyan066** [dexplo/jupyter_to_medium#57]
Please, check the below image, is it an error from my side or in the package? Thank you: 
I get this error while using the plots plotted with plotly.

![Screenshot from 2022-08-17 16-25-47](https://user-images.githubusercontent.com/30195057/185102298-3dc3a282-65b7-4734-a7d0-ab8e64856784.png)

**Comment by mjam03** [comment]
Hi,

Sorry for the late response - currently the package doesn't support plots with plotly as per this issue:

https://github.com/dexplo/jupyter_to_medium/issues/33

It might  be something for the future or if you fancy getting stuck in and creating a PR that would be great.

Thanks,
Mark
