### ISSUE TITLE
BUG: groupby table image doesn't match output format

### ISSUE THREAD

**Issue by discdiver** [dexplo/jupyter_to_medium#7]
Thanks for your quick turn around today, Ted!

Found a new issue.

The resulting image from a groupby combines the multi-indexes.

Maybe this is an issue with all multi-indexes? I haven't explored.

Using matplotlib to convert the image.
Using jtm v 0.1.1

Screenshots of the output from the same cell in Jupyter and as displayed in Medium are attached.

![Screen Shot 2020-06-26 at 11 42 21 PM](https://user-images.githubusercontent.com/7703961/85913919-0b2cf900-b807-11ea-8da0-335bb23364b3.png)
![Screen Shot 2020-06-26 at 11 42 14 PM](https://user-images.githubusercontent.com/7703961/85913925-154ef780-b807-11ea-9088-8c639da7f20e.png)

**Comment by tdpetrou** [comment]
I'm working on this, should have something out soon.

**Comment by tdpetrou** [comment]
I made a big update to how matplotlib creates tables. Images are much nicer now. pandas groupby tables are almost there. The index values just repeat. I might try and get it to look exactly the same, but I'm happy with the improvement and will close the issue.

Can you upgrade to version 0.2, test, and report back here?
