### ISSUE TITLE
Feature Request: option to keep user-provided images at higher resolution

### ISSUE THREAD

**Issue by discdiver** [dexplo/jupyter_to_medium#8]
In Medium, I notice I can't set any of the images I added to my notebook to be full screen or semi-full screen. The resolution of the images when added to my original notebook was quite high. I believe the images need to be saved at higher resolution for this option to appear in Medium. 

If this is the issue, it would be nice to somehow be able to specify keeping the original resolution for all user generated images, or to specify for one image at a time. Not a huge deal, I can just delete and upload a new image to Medium directly. But usually I want at least 2 higher resolution images in a post.

**Comment by tdpetrou** [comment]
Interesting. I just checked this myself and verified that images cannot be used for semi/full screen. Unfortunately, I don't believe it's possible to do anything about this as the API has no parameter settings to change the resolution. 

You can check the API here - https://github.com/Medium/medium-api-docs#34-images

If you think you can do something about this, reopen this issue.
